config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about_me', to: 'pages#index'
  get 'home', to: 'pages#home'
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update_attributes(job_params)
    redirect_to jobs_path
  end

  def new
    @job = Job.new
  end

  def create
    Job.create(job_params)
    redirect_to new_job_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :from, :to, :employer)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @jobs = Job.all
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |form| %>
  <p>
    <%= form.input :title %>
  </p>
  <p>
    <%= form.input :from %>
  </p>
  <p>
    <%= form.input :to %>
  </p>
  <p>
    <%= form.button :submit %>
  </p>
<% end %>

app/views/jobs/edit.html.erb
<h1> Edit job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<ul>
<% @jobs.each do |job| %>
<li>
<%= job.id %>
<%= job.title %>
<%= link_to 'Edit Job', edit_job_path(job) %>
<%= link_to 'Destroy Job', job, method: :delete %>
</ls>
<% end %>
</ul>

app/views/jobs/new.html.erb
<h1> Create new job</h1>

<%= render 'form' %>


<!--
<%= form_with model: @job do |form| %>
  <p>
    <%= form.label :title %> </br>
    <%= form.text_field :title%>
  </p>

  <p>
    <%= form.label :from %> </br>
    <%= form.date_field :from %>
  </p>

  <p>
    <%= form.label :to %> </br>
    <%= form.date_field :to %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/pages/index.html.erb
<h1>Hello World</h1>

<ul>
  <% @jobs.each do |job| %>
  <li><%= job.title %><br></li>
  <li><%= job.employer %><br></li>
  <li><%= job.description %><br></li>
  <li><%= job.from %><br></li>
  <li><%= job.to %><br></li>
  <% end %>
</ul>